# Generated by Django 2.2.24 on 2023-10-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, choices=[(True, 'Новостройка'), (False, 'Старое здание'), (None, 'Не заполнено')], null=True, verbose_name='Новостройка'),
        ),
    ]
