# Generated by Django 2.2.24 on 2023-10-31 11:50

from django.db import migrations


def fill_empty_boxes(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if not flat.construction_year:
            continue
        if flat.construction_year >= 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20231031_1134'),
    ]

    operations = [
        migrations.RunPython(fill_empty_boxes)
    ]
