# Generated by Django 2.2.24 on 2023-10-31 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20231031_1538'),
        ('property', '0005_auto_20231031_1450'),
    ]

    operations = [
    ]
