# Generated by Django 2.2.24 on 2023-11-01 16:45

from django.db import migrations
import phonenumbers


def normalize_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        normal_number = phonenumbers.parse(
            flat.owners_phonenumber, "RU"
        )
        if phonenumbers.is_valid_number(normal_number):
            flat.owner_pure_phone = normal_number
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20231031_1757'),
    ]

    operations = [
        migrations.RunPython(normalize_number)
    ]
