# Generated by Django 2.2.24 on 2023-11-02 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20231102_0820'),
        ('property', '0015_auto_20231102_0820'),
    ]

    operations = [
    ]
