# Generated by Django 2.2.24 on 2023-11-04 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20231104_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
