# Generated by Django 2.2.24 on 2023-11-05 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_auto_20231105_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owned_by',
            new_name='flats',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complained', to='property.Flat', verbose_name='Квартира, на которую пожаловались'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complained', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
    ]
